name: Update file with git commit version
on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  update-file:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: d1
        run: echo "${{git branch}} ${{ github.head_ref }} ${{github.base_ref}}"
        
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
              ref: main
                   
      - name: d2
        run: echo "${{git branch}} ${{ github.head_ref }} ${{github.base_ref}}"
                     
      - name: Get git commit version
        run: echo "::set-output name=version::$(git rev-parse --short HEAD)" > version.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update file with git commit version
          branch: ${{ github.base_ref }}
